/*
Nango API

Nango API specs used to authorize & sync data with external APIs.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nango

import (
	"encoding/json"
)

// checks if the ConnectionMetadataPatch200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectionMetadataPatch200Response{}

// ConnectionMetadataPatch200Response struct for ConnectionMetadataPatch200Response
type ConnectionMetadataPatch200Response struct {
	ConnectionId *ConnectionMetadataPatch200ResponseConnectionId `json:"connection_id,omitempty"`
	// The integration ID used to create the connection (aka Unique Key).
	ProviderConfigKey *string `json:"provider_config_key,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// NewConnectionMetadataPatch200Response instantiates a new ConnectionMetadataPatch200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectionMetadataPatch200Response() *ConnectionMetadataPatch200Response {
	this := ConnectionMetadataPatch200Response{}
	return &this
}

// NewConnectionMetadataPatch200ResponseWithDefaults instantiates a new ConnectionMetadataPatch200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionMetadataPatch200ResponseWithDefaults() *ConnectionMetadataPatch200Response {
	this := ConnectionMetadataPatch200Response{}
	return &this
}

// GetConnectionId returns the ConnectionId field value if set, zero value otherwise.
func (o *ConnectionMetadataPatch200Response) GetConnectionId() ConnectionMetadataPatch200ResponseConnectionId {
	if o == nil || IsNil(o.ConnectionId) {
		var ret ConnectionMetadataPatch200ResponseConnectionId
		return ret
	}
	return *o.ConnectionId
}

// GetConnectionIdOk returns a tuple with the ConnectionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionMetadataPatch200Response) GetConnectionIdOk() (*ConnectionMetadataPatch200ResponseConnectionId, bool) {
	if o == nil || IsNil(o.ConnectionId) {
		return nil, false
	}
	return o.ConnectionId, true
}

// HasConnectionId returns a boolean if a field has been set.
func (o *ConnectionMetadataPatch200Response) HasConnectionId() bool {
	if o != nil && !IsNil(o.ConnectionId) {
		return true
	}

	return false
}

// SetConnectionId gets a reference to the given ConnectionMetadataPatch200ResponseConnectionId and assigns it to the ConnectionId field.
func (o *ConnectionMetadataPatch200Response) SetConnectionId(v ConnectionMetadataPatch200ResponseConnectionId) {
	o.ConnectionId = &v
}

// GetProviderConfigKey returns the ProviderConfigKey field value if set, zero value otherwise.
func (o *ConnectionMetadataPatch200Response) GetProviderConfigKey() string {
	if o == nil || IsNil(o.ProviderConfigKey) {
		var ret string
		return ret
	}
	return *o.ProviderConfigKey
}

// GetProviderConfigKeyOk returns a tuple with the ProviderConfigKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionMetadataPatch200Response) GetProviderConfigKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ProviderConfigKey) {
		return nil, false
	}
	return o.ProviderConfigKey, true
}

// HasProviderConfigKey returns a boolean if a field has been set.
func (o *ConnectionMetadataPatch200Response) HasProviderConfigKey() bool {
	if o != nil && !IsNil(o.ProviderConfigKey) {
		return true
	}

	return false
}

// SetProviderConfigKey gets a reference to the given string and assigns it to the ProviderConfigKey field.
func (o *ConnectionMetadataPatch200Response) SetProviderConfigKey(v string) {
	o.ProviderConfigKey = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ConnectionMetadataPatch200Response) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionMetadataPatch200Response) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ConnectionMetadataPatch200Response) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *ConnectionMetadataPatch200Response) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o ConnectionMetadataPatch200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectionMetadataPatch200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConnectionId) {
		toSerialize["connection_id"] = o.ConnectionId
	}
	if !IsNil(o.ProviderConfigKey) {
		toSerialize["provider_config_key"] = o.ProviderConfigKey
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullableConnectionMetadataPatch200Response struct {
	value *ConnectionMetadataPatch200Response
	isSet bool
}

func (v NullableConnectionMetadataPatch200Response) Get() *ConnectionMetadataPatch200Response {
	return v.value
}

func (v *NullableConnectionMetadataPatch200Response) Set(val *ConnectionMetadataPatch200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionMetadataPatch200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionMetadataPatch200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionMetadataPatch200Response(val *ConnectionMetadataPatch200Response) *NullableConnectionMetadataPatch200Response {
	return &NullableConnectionMetadataPatch200Response{value: val, isSet: true}
}

func (v NullableConnectionMetadataPatch200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionMetadataPatch200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


