/*
Nango API

Nango API specs used to authorize & sync data with external APIs.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nango

import (
	"encoding/json"
)

// checks if the ScriptsConfigGet200ResponseSyncsInnerModelsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScriptsConfigGet200ResponseSyncsInnerModelsInner{}

// ScriptsConfigGet200ResponseSyncsInnerModelsInner struct for ScriptsConfigGet200ResponseSyncsInnerModelsInner
type ScriptsConfigGet200ResponseSyncsInnerModelsInner struct {
	Name *string `json:"name,omitempty"`
	Fields []ScriptsConfigGet200ResponseSyncsInnerModelsInnerFieldsInner `json:"fields,omitempty"`
}

// NewScriptsConfigGet200ResponseSyncsInnerModelsInner instantiates a new ScriptsConfigGet200ResponseSyncsInnerModelsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScriptsConfigGet200ResponseSyncsInnerModelsInner() *ScriptsConfigGet200ResponseSyncsInnerModelsInner {
	this := ScriptsConfigGet200ResponseSyncsInnerModelsInner{}
	return &this
}

// NewScriptsConfigGet200ResponseSyncsInnerModelsInnerWithDefaults instantiates a new ScriptsConfigGet200ResponseSyncsInnerModelsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScriptsConfigGet200ResponseSyncsInnerModelsInnerWithDefaults() *ScriptsConfigGet200ResponseSyncsInnerModelsInner {
	this := ScriptsConfigGet200ResponseSyncsInnerModelsInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ScriptsConfigGet200ResponseSyncsInnerModelsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200ResponseSyncsInnerModelsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ScriptsConfigGet200ResponseSyncsInnerModelsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ScriptsConfigGet200ResponseSyncsInnerModelsInner) SetName(v string) {
	o.Name = &v
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *ScriptsConfigGet200ResponseSyncsInnerModelsInner) GetFields() []ScriptsConfigGet200ResponseSyncsInnerModelsInnerFieldsInner {
	if o == nil || IsNil(o.Fields) {
		var ret []ScriptsConfigGet200ResponseSyncsInnerModelsInnerFieldsInner
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200ResponseSyncsInnerModelsInner) GetFieldsOk() ([]ScriptsConfigGet200ResponseSyncsInnerModelsInnerFieldsInner, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *ScriptsConfigGet200ResponseSyncsInnerModelsInner) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given []ScriptsConfigGet200ResponseSyncsInnerModelsInnerFieldsInner and assigns it to the Fields field.
func (o *ScriptsConfigGet200ResponseSyncsInnerModelsInner) SetFields(v []ScriptsConfigGet200ResponseSyncsInnerModelsInnerFieldsInner) {
	o.Fields = v
}

func (o ScriptsConfigGet200ResponseSyncsInnerModelsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScriptsConfigGet200ResponseSyncsInnerModelsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}
	return toSerialize, nil
}

type NullableScriptsConfigGet200ResponseSyncsInnerModelsInner struct {
	value *ScriptsConfigGet200ResponseSyncsInnerModelsInner
	isSet bool
}

func (v NullableScriptsConfigGet200ResponseSyncsInnerModelsInner) Get() *ScriptsConfigGet200ResponseSyncsInnerModelsInner {
	return v.value
}

func (v *NullableScriptsConfigGet200ResponseSyncsInnerModelsInner) Set(val *ScriptsConfigGet200ResponseSyncsInnerModelsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableScriptsConfigGet200ResponseSyncsInnerModelsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableScriptsConfigGet200ResponseSyncsInnerModelsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScriptsConfigGet200ResponseSyncsInnerModelsInner(val *ScriptsConfigGet200ResponseSyncsInnerModelsInner) *NullableScriptsConfigGet200ResponseSyncsInnerModelsInner {
	return &NullableScriptsConfigGet200ResponseSyncsInnerModelsInner{value: val, isSet: true}
}

func (v NullableScriptsConfigGet200ResponseSyncsInnerModelsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScriptsConfigGet200ResponseSyncsInnerModelsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


