/*
Nango API

Nango API specs used to authorize & sync data with external APIs.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nango

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SyncStartPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SyncStartPostRequest{}

// SyncStartPostRequest struct for SyncStartPostRequest
type SyncStartPostRequest struct {
	// The ID of the integration that you established within Nango.
	ProviderConfigKey string `json:"provider_config_key"`
	// The ID of the connection. If omitted, the syncs will be started for all relevant connections.
	ConnectionId *string `json:"connection_id,omitempty"`
	// A list of sync names that you wish to start.
	Syncs []string `json:"syncs"`
}

type _SyncStartPostRequest SyncStartPostRequest

// NewSyncStartPostRequest instantiates a new SyncStartPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyncStartPostRequest(providerConfigKey string, syncs []string) *SyncStartPostRequest {
	this := SyncStartPostRequest{}
	this.ProviderConfigKey = providerConfigKey
	this.Syncs = syncs
	return &this
}

// NewSyncStartPostRequestWithDefaults instantiates a new SyncStartPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyncStartPostRequestWithDefaults() *SyncStartPostRequest {
	this := SyncStartPostRequest{}
	return &this
}

// GetProviderConfigKey returns the ProviderConfigKey field value
func (o *SyncStartPostRequest) GetProviderConfigKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderConfigKey
}

// GetProviderConfigKeyOk returns a tuple with the ProviderConfigKey field value
// and a boolean to check if the value has been set.
func (o *SyncStartPostRequest) GetProviderConfigKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderConfigKey, true
}

// SetProviderConfigKey sets field value
func (o *SyncStartPostRequest) SetProviderConfigKey(v string) {
	o.ProviderConfigKey = v
}

// GetConnectionId returns the ConnectionId field value if set, zero value otherwise.
func (o *SyncStartPostRequest) GetConnectionId() string {
	if o == nil || IsNil(o.ConnectionId) {
		var ret string
		return ret
	}
	return *o.ConnectionId
}

// GetConnectionIdOk returns a tuple with the ConnectionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyncStartPostRequest) GetConnectionIdOk() (*string, bool) {
	if o == nil || IsNil(o.ConnectionId) {
		return nil, false
	}
	return o.ConnectionId, true
}

// HasConnectionId returns a boolean if a field has been set.
func (o *SyncStartPostRequest) HasConnectionId() bool {
	if o != nil && !IsNil(o.ConnectionId) {
		return true
	}

	return false
}

// SetConnectionId gets a reference to the given string and assigns it to the ConnectionId field.
func (o *SyncStartPostRequest) SetConnectionId(v string) {
	o.ConnectionId = &v
}

// GetSyncs returns the Syncs field value
func (o *SyncStartPostRequest) GetSyncs() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Syncs
}

// GetSyncsOk returns a tuple with the Syncs field value
// and a boolean to check if the value has been set.
func (o *SyncStartPostRequest) GetSyncsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Syncs, true
}

// SetSyncs sets field value
func (o *SyncStartPostRequest) SetSyncs(v []string) {
	o.Syncs = v
}

func (o SyncStartPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SyncStartPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["provider_config_key"] = o.ProviderConfigKey
	if !IsNil(o.ConnectionId) {
		toSerialize["connection_id"] = o.ConnectionId
	}
	toSerialize["syncs"] = o.Syncs
	return toSerialize, nil
}

func (o *SyncStartPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"provider_config_key",
		"syncs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSyncStartPostRequest := _SyncStartPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSyncStartPostRequest)

	if err != nil {
		return err
	}

	*o = SyncStartPostRequest(varSyncStartPostRequest)

	return err
}

type NullableSyncStartPostRequest struct {
	value *SyncStartPostRequest
	isSet bool
}

func (v NullableSyncStartPostRequest) Get() *SyncStartPostRequest {
	return v.value
}

func (v *NullableSyncStartPostRequest) Set(val *SyncStartPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSyncStartPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSyncStartPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyncStartPostRequest(val *SyncStartPostRequest) *NullableSyncStartPostRequest {
	return &NullableSyncStartPostRequest{value: val, isSet: true}
}

func (v NullableSyncStartPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyncStartPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


