/*
Nango API

Nango API specs used to authorize & sync data with external APIs.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nango

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConfigPut200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigPut200Response{}

// ConfigPut200Response struct for ConfigPut200Response
type ConfigPut200Response struct {
	Config ConfigGet200ResponseConfigsInner `json:"config"`
}

type _ConfigPut200Response ConfigPut200Response

// NewConfigPut200Response instantiates a new ConfigPut200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigPut200Response(config ConfigGet200ResponseConfigsInner) *ConfigPut200Response {
	this := ConfigPut200Response{}
	this.Config = config
	return &this
}

// NewConfigPut200ResponseWithDefaults instantiates a new ConfigPut200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigPut200ResponseWithDefaults() *ConfigPut200Response {
	this := ConfigPut200Response{}
	return &this
}

// GetConfig returns the Config field value
func (o *ConfigPut200Response) GetConfig() ConfigGet200ResponseConfigsInner {
	if o == nil {
		var ret ConfigGet200ResponseConfigsInner
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *ConfigPut200Response) GetConfigOk() (*ConfigGet200ResponseConfigsInner, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Config, true
}

// SetConfig sets field value
func (o *ConfigPut200Response) SetConfig(v ConfigGet200ResponseConfigsInner) {
	o.Config = v
}

func (o ConfigPut200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigPut200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["config"] = o.Config
	return toSerialize, nil
}

func (o *ConfigPut200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"config",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigPut200Response := _ConfigPut200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfigPut200Response)

	if err != nil {
		return err
	}

	*o = ConfigPut200Response(varConfigPut200Response)

	return err
}

type NullableConfigPut200Response struct {
	value *ConfigPut200Response
	isSet bool
}

func (v NullableConfigPut200Response) Get() *ConfigPut200Response {
	return v.value
}

func (v *NullableConfigPut200Response) Set(val *ConfigPut200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigPut200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigPut200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigPut200Response(val *ConfigPut200Response) *NullableConfigPut200Response {
	return &NullableConfigPut200Response{value: val, isSet: true}
}

func (v NullableConfigPut200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigPut200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


