/*
Nango API

Nango API specs used to authorize & sync data with external APIs.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nango

import (
	"encoding/json"
)

// checks if the ScriptsConfigGet200ResponseActionsInnerModelsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScriptsConfigGet200ResponseActionsInnerModelsInner{}

// ScriptsConfigGet200ResponseActionsInnerModelsInner struct for ScriptsConfigGet200ResponseActionsInnerModelsInner
type ScriptsConfigGet200ResponseActionsInnerModelsInner struct {
	Name *string `json:"name,omitempty"`
	Fields []ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner `json:"fields,omitempty"`
}

// NewScriptsConfigGet200ResponseActionsInnerModelsInner instantiates a new ScriptsConfigGet200ResponseActionsInnerModelsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScriptsConfigGet200ResponseActionsInnerModelsInner() *ScriptsConfigGet200ResponseActionsInnerModelsInner {
	this := ScriptsConfigGet200ResponseActionsInnerModelsInner{}
	return &this
}

// NewScriptsConfigGet200ResponseActionsInnerModelsInnerWithDefaults instantiates a new ScriptsConfigGet200ResponseActionsInnerModelsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScriptsConfigGet200ResponseActionsInnerModelsInnerWithDefaults() *ScriptsConfigGet200ResponseActionsInnerModelsInner {
	this := ScriptsConfigGet200ResponseActionsInnerModelsInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ScriptsConfigGet200ResponseActionsInnerModelsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200ResponseActionsInnerModelsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ScriptsConfigGet200ResponseActionsInnerModelsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ScriptsConfigGet200ResponseActionsInnerModelsInner) SetName(v string) {
	o.Name = &v
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *ScriptsConfigGet200ResponseActionsInnerModelsInner) GetFields() []ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner {
	if o == nil || IsNil(o.Fields) {
		var ret []ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200ResponseActionsInnerModelsInner) GetFieldsOk() ([]ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *ScriptsConfigGet200ResponseActionsInnerModelsInner) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given []ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner and assigns it to the Fields field.
func (o *ScriptsConfigGet200ResponseActionsInnerModelsInner) SetFields(v []ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner) {
	o.Fields = v
}

func (o ScriptsConfigGet200ResponseActionsInnerModelsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScriptsConfigGet200ResponseActionsInnerModelsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}
	return toSerialize, nil
}

type NullableScriptsConfigGet200ResponseActionsInnerModelsInner struct {
	value *ScriptsConfigGet200ResponseActionsInnerModelsInner
	isSet bool
}

func (v NullableScriptsConfigGet200ResponseActionsInnerModelsInner) Get() *ScriptsConfigGet200ResponseActionsInnerModelsInner {
	return v.value
}

func (v *NullableScriptsConfigGet200ResponseActionsInnerModelsInner) Set(val *ScriptsConfigGet200ResponseActionsInnerModelsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableScriptsConfigGet200ResponseActionsInnerModelsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableScriptsConfigGet200ResponseActionsInnerModelsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScriptsConfigGet200ResponseActionsInnerModelsInner(val *ScriptsConfigGet200ResponseActionsInnerModelsInner) *NullableScriptsConfigGet200ResponseActionsInnerModelsInner {
	return &NullableScriptsConfigGet200ResponseActionsInnerModelsInner{value: val, isSet: true}
}

func (v NullableScriptsConfigGet200ResponseActionsInnerModelsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScriptsConfigGet200ResponseActionsInnerModelsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


