/*
Nango API

Nango API specs used to authorize & sync data with external APIs.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nango

import (
	"encoding/json"
)

// checks if the ConfigProviderConfigKeyGet200ResponseConfigActionsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigProviderConfigKeyGet200ResponseConfigActionsInner{}

// ConfigProviderConfigKeyGet200ResponseConfigActionsInner struct for ConfigProviderConfigKeyGet200ResponseConfigActionsInner
type ConfigProviderConfigKeyGet200ResponseConfigActionsInner struct {
	// The name of the action.
	Name *string `json:"name,omitempty"`
	// The creation timestamp of the sync.
	CreatedAt *string `json:"created_at,omitempty"`
	// The last updated timestamp of the sync.
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// NewConfigProviderConfigKeyGet200ResponseConfigActionsInner instantiates a new ConfigProviderConfigKeyGet200ResponseConfigActionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigProviderConfigKeyGet200ResponseConfigActionsInner() *ConfigProviderConfigKeyGet200ResponseConfigActionsInner {
	this := ConfigProviderConfigKeyGet200ResponseConfigActionsInner{}
	return &this
}

// NewConfigProviderConfigKeyGet200ResponseConfigActionsInnerWithDefaults instantiates a new ConfigProviderConfigKeyGet200ResponseConfigActionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigProviderConfigKeyGet200ResponseConfigActionsInnerWithDefaults() *ConfigProviderConfigKeyGet200ResponseConfigActionsInner {
	this := ConfigProviderConfigKeyGet200ResponseConfigActionsInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ConfigProviderConfigKeyGet200ResponseConfigActionsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigProviderConfigKeyGet200ResponseConfigActionsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ConfigProviderConfigKeyGet200ResponseConfigActionsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ConfigProviderConfigKeyGet200ResponseConfigActionsInner) SetName(v string) {
	o.Name = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ConfigProviderConfigKeyGet200ResponseConfigActionsInner) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigProviderConfigKeyGet200ResponseConfigActionsInner) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ConfigProviderConfigKeyGet200ResponseConfigActionsInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ConfigProviderConfigKeyGet200ResponseConfigActionsInner) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ConfigProviderConfigKeyGet200ResponseConfigActionsInner) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigProviderConfigKeyGet200ResponseConfigActionsInner) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ConfigProviderConfigKeyGet200ResponseConfigActionsInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *ConfigProviderConfigKeyGet200ResponseConfigActionsInner) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o ConfigProviderConfigKeyGet200ResponseConfigActionsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigProviderConfigKeyGet200ResponseConfigActionsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableConfigProviderConfigKeyGet200ResponseConfigActionsInner struct {
	value *ConfigProviderConfigKeyGet200ResponseConfigActionsInner
	isSet bool
}

func (v NullableConfigProviderConfigKeyGet200ResponseConfigActionsInner) Get() *ConfigProviderConfigKeyGet200ResponseConfigActionsInner {
	return v.value
}

func (v *NullableConfigProviderConfigKeyGet200ResponseConfigActionsInner) Set(val *ConfigProviderConfigKeyGet200ResponseConfigActionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigProviderConfigKeyGet200ResponseConfigActionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigProviderConfigKeyGet200ResponseConfigActionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigProviderConfigKeyGet200ResponseConfigActionsInner(val *ConfigProviderConfigKeyGet200ResponseConfigActionsInner) *NullableConfigProviderConfigKeyGet200ResponseConfigActionsInner {
	return &NullableConfigProviderConfigKeyGet200ResponseConfigActionsInner{value: val, isSet: true}
}

func (v NullableConfigProviderConfigKeyGet200ResponseConfigActionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigProviderConfigKeyGet200ResponseConfigActionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


