/*
Nango API

Nango API specs used to authorize & sync data with external APIs.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nango

import (
	"encoding/json"
)

// checks if the RecordsGet200ResponseRecordsInnerNangoMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecordsGet200ResponseRecordsInnerNangoMetadata{}

// RecordsGet200ResponseRecordsInnerNangoMetadata struct for RecordsGet200ResponseRecordsInnerNangoMetadata
type RecordsGet200ResponseRecordsInnerNangoMetadata struct {
	// The timestamp at which Nango detected the record as deleted
	DeletedAt *string `json:"deleted_at,omitempty"`
	// The last action seen on this record
	LastAction *string `json:"last_action,omitempty"`
	// The timestamp at which Nango first saw this record
	FirstSeenAt *string `json:"first_seen_at,omitempty"`
	// The timestamp at which Nango last detected a change to this record
	LastModifiedAt *string `json:"last_modified_at,omitempty"`
	// The current cursor of the record. Use this to fetch records updated after this record
	Cursor *string `json:"cursor,omitempty"`
}

// NewRecordsGet200ResponseRecordsInnerNangoMetadata instantiates a new RecordsGet200ResponseRecordsInnerNangoMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecordsGet200ResponseRecordsInnerNangoMetadata() *RecordsGet200ResponseRecordsInnerNangoMetadata {
	this := RecordsGet200ResponseRecordsInnerNangoMetadata{}
	return &this
}

// NewRecordsGet200ResponseRecordsInnerNangoMetadataWithDefaults instantiates a new RecordsGet200ResponseRecordsInnerNangoMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecordsGet200ResponseRecordsInnerNangoMetadataWithDefaults() *RecordsGet200ResponseRecordsInnerNangoMetadata {
	this := RecordsGet200ResponseRecordsInnerNangoMetadata{}
	return &this
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise.
func (o *RecordsGet200ResponseRecordsInnerNangoMetadata) GetDeletedAt() string {
	if o == nil || IsNil(o.DeletedAt) {
		var ret string
		return ret
	}
	return *o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecordsGet200ResponseRecordsInnerNangoMetadata) GetDeletedAtOk() (*string, bool) {
	if o == nil || IsNil(o.DeletedAt) {
		return nil, false
	}
	return o.DeletedAt, true
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *RecordsGet200ResponseRecordsInnerNangoMetadata) HasDeletedAt() bool {
	if o != nil && !IsNil(o.DeletedAt) {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given string and assigns it to the DeletedAt field.
func (o *RecordsGet200ResponseRecordsInnerNangoMetadata) SetDeletedAt(v string) {
	o.DeletedAt = &v
}

// GetLastAction returns the LastAction field value if set, zero value otherwise.
func (o *RecordsGet200ResponseRecordsInnerNangoMetadata) GetLastAction() string {
	if o == nil || IsNil(o.LastAction) {
		var ret string
		return ret
	}
	return *o.LastAction
}

// GetLastActionOk returns a tuple with the LastAction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecordsGet200ResponseRecordsInnerNangoMetadata) GetLastActionOk() (*string, bool) {
	if o == nil || IsNil(o.LastAction) {
		return nil, false
	}
	return o.LastAction, true
}

// HasLastAction returns a boolean if a field has been set.
func (o *RecordsGet200ResponseRecordsInnerNangoMetadata) HasLastAction() bool {
	if o != nil && !IsNil(o.LastAction) {
		return true
	}

	return false
}

// SetLastAction gets a reference to the given string and assigns it to the LastAction field.
func (o *RecordsGet200ResponseRecordsInnerNangoMetadata) SetLastAction(v string) {
	o.LastAction = &v
}

// GetFirstSeenAt returns the FirstSeenAt field value if set, zero value otherwise.
func (o *RecordsGet200ResponseRecordsInnerNangoMetadata) GetFirstSeenAt() string {
	if o == nil || IsNil(o.FirstSeenAt) {
		var ret string
		return ret
	}
	return *o.FirstSeenAt
}

// GetFirstSeenAtOk returns a tuple with the FirstSeenAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecordsGet200ResponseRecordsInnerNangoMetadata) GetFirstSeenAtOk() (*string, bool) {
	if o == nil || IsNil(o.FirstSeenAt) {
		return nil, false
	}
	return o.FirstSeenAt, true
}

// HasFirstSeenAt returns a boolean if a field has been set.
func (o *RecordsGet200ResponseRecordsInnerNangoMetadata) HasFirstSeenAt() bool {
	if o != nil && !IsNil(o.FirstSeenAt) {
		return true
	}

	return false
}

// SetFirstSeenAt gets a reference to the given string and assigns it to the FirstSeenAt field.
func (o *RecordsGet200ResponseRecordsInnerNangoMetadata) SetFirstSeenAt(v string) {
	o.FirstSeenAt = &v
}

// GetLastModifiedAt returns the LastModifiedAt field value if set, zero value otherwise.
func (o *RecordsGet200ResponseRecordsInnerNangoMetadata) GetLastModifiedAt() string {
	if o == nil || IsNil(o.LastModifiedAt) {
		var ret string
		return ret
	}
	return *o.LastModifiedAt
}

// GetLastModifiedAtOk returns a tuple with the LastModifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecordsGet200ResponseRecordsInnerNangoMetadata) GetLastModifiedAtOk() (*string, bool) {
	if o == nil || IsNil(o.LastModifiedAt) {
		return nil, false
	}
	return o.LastModifiedAt, true
}

// HasLastModifiedAt returns a boolean if a field has been set.
func (o *RecordsGet200ResponseRecordsInnerNangoMetadata) HasLastModifiedAt() bool {
	if o != nil && !IsNil(o.LastModifiedAt) {
		return true
	}

	return false
}

// SetLastModifiedAt gets a reference to the given string and assigns it to the LastModifiedAt field.
func (o *RecordsGet200ResponseRecordsInnerNangoMetadata) SetLastModifiedAt(v string) {
	o.LastModifiedAt = &v
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *RecordsGet200ResponseRecordsInnerNangoMetadata) GetCursor() string {
	if o == nil || IsNil(o.Cursor) {
		var ret string
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecordsGet200ResponseRecordsInnerNangoMetadata) GetCursorOk() (*string, bool) {
	if o == nil || IsNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *RecordsGet200ResponseRecordsInnerNangoMetadata) HasCursor() bool {
	if o != nil && !IsNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given string and assigns it to the Cursor field.
func (o *RecordsGet200ResponseRecordsInnerNangoMetadata) SetCursor(v string) {
	o.Cursor = &v
}

func (o RecordsGet200ResponseRecordsInnerNangoMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecordsGet200ResponseRecordsInnerNangoMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeletedAt) {
		toSerialize["deleted_at"] = o.DeletedAt
	}
	if !IsNil(o.LastAction) {
		toSerialize["last_action"] = o.LastAction
	}
	if !IsNil(o.FirstSeenAt) {
		toSerialize["first_seen_at"] = o.FirstSeenAt
	}
	if !IsNil(o.LastModifiedAt) {
		toSerialize["last_modified_at"] = o.LastModifiedAt
	}
	if !IsNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	return toSerialize, nil
}

type NullableRecordsGet200ResponseRecordsInnerNangoMetadata struct {
	value *RecordsGet200ResponseRecordsInnerNangoMetadata
	isSet bool
}

func (v NullableRecordsGet200ResponseRecordsInnerNangoMetadata) Get() *RecordsGet200ResponseRecordsInnerNangoMetadata {
	return v.value
}

func (v *NullableRecordsGet200ResponseRecordsInnerNangoMetadata) Set(val *RecordsGet200ResponseRecordsInnerNangoMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableRecordsGet200ResponseRecordsInnerNangoMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableRecordsGet200ResponseRecordsInnerNangoMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecordsGet200ResponseRecordsInnerNangoMetadata(val *RecordsGet200ResponseRecordsInnerNangoMetadata) *NullableRecordsGet200ResponseRecordsInnerNangoMetadata {
	return &NullableRecordsGet200ResponseRecordsInnerNangoMetadata{value: val, isSet: true}
}

func (v NullableRecordsGet200ResponseRecordsInnerNangoMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecordsGet200ResponseRecordsInnerNangoMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


