/*
Nango API

Nango API specs used to authorize & sync data with external APIs.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nango

import (
	"encoding/json"
)

// checks if the ScriptsConfigGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScriptsConfigGet200Response{}

// ScriptsConfigGet200Response struct for ScriptsConfigGet200Response
type ScriptsConfigGet200Response struct {
	ProviderConfigKey *string `json:"providerConfigKey,omitempty"`
	Syncs []ScriptsConfigGet200ResponseSyncsInner `json:"syncs,omitempty"`
	Actions []ScriptsConfigGet200ResponseActionsInner `json:"actions,omitempty"`
	PostConnectionScripts []string `json:"postConnectionScripts,omitempty"`
	Provider *string `json:"provider,omitempty"`
}

// NewScriptsConfigGet200Response instantiates a new ScriptsConfigGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScriptsConfigGet200Response() *ScriptsConfigGet200Response {
	this := ScriptsConfigGet200Response{}
	return &this
}

// NewScriptsConfigGet200ResponseWithDefaults instantiates a new ScriptsConfigGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScriptsConfigGet200ResponseWithDefaults() *ScriptsConfigGet200Response {
	this := ScriptsConfigGet200Response{}
	return &this
}

// GetProviderConfigKey returns the ProviderConfigKey field value if set, zero value otherwise.
func (o *ScriptsConfigGet200Response) GetProviderConfigKey() string {
	if o == nil || IsNil(o.ProviderConfigKey) {
		var ret string
		return ret
	}
	return *o.ProviderConfigKey
}

// GetProviderConfigKeyOk returns a tuple with the ProviderConfigKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200Response) GetProviderConfigKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ProviderConfigKey) {
		return nil, false
	}
	return o.ProviderConfigKey, true
}

// HasProviderConfigKey returns a boolean if a field has been set.
func (o *ScriptsConfigGet200Response) HasProviderConfigKey() bool {
	if o != nil && !IsNil(o.ProviderConfigKey) {
		return true
	}

	return false
}

// SetProviderConfigKey gets a reference to the given string and assigns it to the ProviderConfigKey field.
func (o *ScriptsConfigGet200Response) SetProviderConfigKey(v string) {
	o.ProviderConfigKey = &v
}

// GetSyncs returns the Syncs field value if set, zero value otherwise.
func (o *ScriptsConfigGet200Response) GetSyncs() []ScriptsConfigGet200ResponseSyncsInner {
	if o == nil || IsNil(o.Syncs) {
		var ret []ScriptsConfigGet200ResponseSyncsInner
		return ret
	}
	return o.Syncs
}

// GetSyncsOk returns a tuple with the Syncs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200Response) GetSyncsOk() ([]ScriptsConfigGet200ResponseSyncsInner, bool) {
	if o == nil || IsNil(o.Syncs) {
		return nil, false
	}
	return o.Syncs, true
}

// HasSyncs returns a boolean if a field has been set.
func (o *ScriptsConfigGet200Response) HasSyncs() bool {
	if o != nil && !IsNil(o.Syncs) {
		return true
	}

	return false
}

// SetSyncs gets a reference to the given []ScriptsConfigGet200ResponseSyncsInner and assigns it to the Syncs field.
func (o *ScriptsConfigGet200Response) SetSyncs(v []ScriptsConfigGet200ResponseSyncsInner) {
	o.Syncs = v
}

// GetActions returns the Actions field value if set, zero value otherwise.
func (o *ScriptsConfigGet200Response) GetActions() []ScriptsConfigGet200ResponseActionsInner {
	if o == nil || IsNil(o.Actions) {
		var ret []ScriptsConfigGet200ResponseActionsInner
		return ret
	}
	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200Response) GetActionsOk() ([]ScriptsConfigGet200ResponseActionsInner, bool) {
	if o == nil || IsNil(o.Actions) {
		return nil, false
	}
	return o.Actions, true
}

// HasActions returns a boolean if a field has been set.
func (o *ScriptsConfigGet200Response) HasActions() bool {
	if o != nil && !IsNil(o.Actions) {
		return true
	}

	return false
}

// SetActions gets a reference to the given []ScriptsConfigGet200ResponseActionsInner and assigns it to the Actions field.
func (o *ScriptsConfigGet200Response) SetActions(v []ScriptsConfigGet200ResponseActionsInner) {
	o.Actions = v
}

// GetPostConnectionScripts returns the PostConnectionScripts field value if set, zero value otherwise.
func (o *ScriptsConfigGet200Response) GetPostConnectionScripts() []string {
	if o == nil || IsNil(o.PostConnectionScripts) {
		var ret []string
		return ret
	}
	return o.PostConnectionScripts
}

// GetPostConnectionScriptsOk returns a tuple with the PostConnectionScripts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200Response) GetPostConnectionScriptsOk() ([]string, bool) {
	if o == nil || IsNil(o.PostConnectionScripts) {
		return nil, false
	}
	return o.PostConnectionScripts, true
}

// HasPostConnectionScripts returns a boolean if a field has been set.
func (o *ScriptsConfigGet200Response) HasPostConnectionScripts() bool {
	if o != nil && !IsNil(o.PostConnectionScripts) {
		return true
	}

	return false
}

// SetPostConnectionScripts gets a reference to the given []string and assigns it to the PostConnectionScripts field.
func (o *ScriptsConfigGet200Response) SetPostConnectionScripts(v []string) {
	o.PostConnectionScripts = v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *ScriptsConfigGet200Response) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200Response) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *ScriptsConfigGet200Response) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *ScriptsConfigGet200Response) SetProvider(v string) {
	o.Provider = &v
}

func (o ScriptsConfigGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScriptsConfigGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProviderConfigKey) {
		toSerialize["providerConfigKey"] = o.ProviderConfigKey
	}
	if !IsNil(o.Syncs) {
		toSerialize["syncs"] = o.Syncs
	}
	if !IsNil(o.Actions) {
		toSerialize["actions"] = o.Actions
	}
	if !IsNil(o.PostConnectionScripts) {
		toSerialize["postConnectionScripts"] = o.PostConnectionScripts
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	return toSerialize, nil
}

type NullableScriptsConfigGet200Response struct {
	value *ScriptsConfigGet200Response
	isSet bool
}

func (v NullableScriptsConfigGet200Response) Get() *ScriptsConfigGet200Response {
	return v.value
}

func (v *NullableScriptsConfigGet200Response) Set(val *ScriptsConfigGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableScriptsConfigGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableScriptsConfigGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScriptsConfigGet200Response(val *ScriptsConfigGet200Response) *NullableScriptsConfigGet200Response {
	return &NullableScriptsConfigGet200Response{value: val, isSet: true}
}

func (v NullableScriptsConfigGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScriptsConfigGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


