/*
Nango API

Nango API specs used to authorize & sync data with external APIs.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nango

import (
	"encoding/json"
)

// checks if the SyncRecordsGet200ResponseInnerNangoMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SyncRecordsGet200ResponseInnerNangoMetadata{}

// SyncRecordsGet200ResponseInnerNangoMetadata struct for SyncRecordsGet200ResponseInnerNangoMetadata
type SyncRecordsGet200ResponseInnerNangoMetadata struct {
	// The timestamp at which Nango detected the record as deleted
	DeletedAt *string `json:"deleted_at,omitempty"`
	// The last action seen on this record
	LastAction *string `json:"last_action,omitempty"`
	// The timestamp at which Nango first saw this record
	FirstSeenAt *string `json:"first_seen_at,omitempty"`
	// The timestamp at which Nango last detected a change to this record
	LastModifiedAt *string `json:"last_modified_at,omitempty"`
}

// NewSyncRecordsGet200ResponseInnerNangoMetadata instantiates a new SyncRecordsGet200ResponseInnerNangoMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyncRecordsGet200ResponseInnerNangoMetadata() *SyncRecordsGet200ResponseInnerNangoMetadata {
	this := SyncRecordsGet200ResponseInnerNangoMetadata{}
	return &this
}

// NewSyncRecordsGet200ResponseInnerNangoMetadataWithDefaults instantiates a new SyncRecordsGet200ResponseInnerNangoMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyncRecordsGet200ResponseInnerNangoMetadataWithDefaults() *SyncRecordsGet200ResponseInnerNangoMetadata {
	this := SyncRecordsGet200ResponseInnerNangoMetadata{}
	return &this
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise.
func (o *SyncRecordsGet200ResponseInnerNangoMetadata) GetDeletedAt() string {
	if o == nil || IsNil(o.DeletedAt) {
		var ret string
		return ret
	}
	return *o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyncRecordsGet200ResponseInnerNangoMetadata) GetDeletedAtOk() (*string, bool) {
	if o == nil || IsNil(o.DeletedAt) {
		return nil, false
	}
	return o.DeletedAt, true
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *SyncRecordsGet200ResponseInnerNangoMetadata) HasDeletedAt() bool {
	if o != nil && !IsNil(o.DeletedAt) {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given string and assigns it to the DeletedAt field.
func (o *SyncRecordsGet200ResponseInnerNangoMetadata) SetDeletedAt(v string) {
	o.DeletedAt = &v
}

// GetLastAction returns the LastAction field value if set, zero value otherwise.
func (o *SyncRecordsGet200ResponseInnerNangoMetadata) GetLastAction() string {
	if o == nil || IsNil(o.LastAction) {
		var ret string
		return ret
	}
	return *o.LastAction
}

// GetLastActionOk returns a tuple with the LastAction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyncRecordsGet200ResponseInnerNangoMetadata) GetLastActionOk() (*string, bool) {
	if o == nil || IsNil(o.LastAction) {
		return nil, false
	}
	return o.LastAction, true
}

// HasLastAction returns a boolean if a field has been set.
func (o *SyncRecordsGet200ResponseInnerNangoMetadata) HasLastAction() bool {
	if o != nil && !IsNil(o.LastAction) {
		return true
	}

	return false
}

// SetLastAction gets a reference to the given string and assigns it to the LastAction field.
func (o *SyncRecordsGet200ResponseInnerNangoMetadata) SetLastAction(v string) {
	o.LastAction = &v
}

// GetFirstSeenAt returns the FirstSeenAt field value if set, zero value otherwise.
func (o *SyncRecordsGet200ResponseInnerNangoMetadata) GetFirstSeenAt() string {
	if o == nil || IsNil(o.FirstSeenAt) {
		var ret string
		return ret
	}
	return *o.FirstSeenAt
}

// GetFirstSeenAtOk returns a tuple with the FirstSeenAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyncRecordsGet200ResponseInnerNangoMetadata) GetFirstSeenAtOk() (*string, bool) {
	if o == nil || IsNil(o.FirstSeenAt) {
		return nil, false
	}
	return o.FirstSeenAt, true
}

// HasFirstSeenAt returns a boolean if a field has been set.
func (o *SyncRecordsGet200ResponseInnerNangoMetadata) HasFirstSeenAt() bool {
	if o != nil && !IsNil(o.FirstSeenAt) {
		return true
	}

	return false
}

// SetFirstSeenAt gets a reference to the given string and assigns it to the FirstSeenAt field.
func (o *SyncRecordsGet200ResponseInnerNangoMetadata) SetFirstSeenAt(v string) {
	o.FirstSeenAt = &v
}

// GetLastModifiedAt returns the LastModifiedAt field value if set, zero value otherwise.
func (o *SyncRecordsGet200ResponseInnerNangoMetadata) GetLastModifiedAt() string {
	if o == nil || IsNil(o.LastModifiedAt) {
		var ret string
		return ret
	}
	return *o.LastModifiedAt
}

// GetLastModifiedAtOk returns a tuple with the LastModifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyncRecordsGet200ResponseInnerNangoMetadata) GetLastModifiedAtOk() (*string, bool) {
	if o == nil || IsNil(o.LastModifiedAt) {
		return nil, false
	}
	return o.LastModifiedAt, true
}

// HasLastModifiedAt returns a boolean if a field has been set.
func (o *SyncRecordsGet200ResponseInnerNangoMetadata) HasLastModifiedAt() bool {
	if o != nil && !IsNil(o.LastModifiedAt) {
		return true
	}

	return false
}

// SetLastModifiedAt gets a reference to the given string and assigns it to the LastModifiedAt field.
func (o *SyncRecordsGet200ResponseInnerNangoMetadata) SetLastModifiedAt(v string) {
	o.LastModifiedAt = &v
}

func (o SyncRecordsGet200ResponseInnerNangoMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SyncRecordsGet200ResponseInnerNangoMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeletedAt) {
		toSerialize["deleted_at"] = o.DeletedAt
	}
	if !IsNil(o.LastAction) {
		toSerialize["last_action"] = o.LastAction
	}
	if !IsNil(o.FirstSeenAt) {
		toSerialize["first_seen_at"] = o.FirstSeenAt
	}
	if !IsNil(o.LastModifiedAt) {
		toSerialize["last_modified_at"] = o.LastModifiedAt
	}
	return toSerialize, nil
}

type NullableSyncRecordsGet200ResponseInnerNangoMetadata struct {
	value *SyncRecordsGet200ResponseInnerNangoMetadata
	isSet bool
}

func (v NullableSyncRecordsGet200ResponseInnerNangoMetadata) Get() *SyncRecordsGet200ResponseInnerNangoMetadata {
	return v.value
}

func (v *NullableSyncRecordsGet200ResponseInnerNangoMetadata) Set(val *SyncRecordsGet200ResponseInnerNangoMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableSyncRecordsGet200ResponseInnerNangoMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableSyncRecordsGet200ResponseInnerNangoMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyncRecordsGet200ResponseInnerNangoMetadata(val *SyncRecordsGet200ResponseInnerNangoMetadata) *NullableSyncRecordsGet200ResponseInnerNangoMetadata {
	return &NullableSyncRecordsGet200ResponseInnerNangoMetadata{value: val, isSet: true}
}

func (v NullableSyncRecordsGet200ResponseInnerNangoMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyncRecordsGet200ResponseInnerNangoMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


