/*
Nango API

Nango API specs used to authorize & sync data with external APIs.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nango

import (
	"encoding/json"
)

// checks if the ScriptsConfigGet200ResponseSyncsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScriptsConfigGet200ResponseSyncsInner{}

// ScriptsConfigGet200ResponseSyncsInner struct for ScriptsConfigGet200ResponseSyncsInner
type ScriptsConfigGet200ResponseSyncsInner struct {
	Name *string `json:"name,omitempty"`
	Type *string `json:"type,omitempty"`
	Models []ScriptsConfigGet200ResponseSyncsInnerModelsInner `json:"models,omitempty"`
	SyncType *string `json:"sync_type,omitempty"`
	Runs *string `json:"runs,omitempty"`
	TrackDeletes *bool `json:"track_deletes,omitempty"`
	AutoStart *bool `json:"auto_start,omitempty"`
	LastDeployed *string `json:"last_deployed,omitempty"`
	IsPublic *bool `json:"is_public,omitempty"`
	PreBuilt *bool `json:"pre_built,omitempty"`
	Version *string `json:"version,omitempty"`
	Attributes map[string]interface{} `json:"attributes,omitempty"`
	Input map[string]interface{} `json:"input,omitempty"`
	Returns []string `json:"returns,omitempty"`
	Description *string `json:"description,omitempty"`
	Scopes []string `json:"scopes,omitempty"`
	Endpoints []map[string]interface{} `json:"endpoints,omitempty"`
	NangoYamlVersion *string `json:"nango_yaml_version,omitempty"`
	WebhookSubscriptions []string `json:"webhookSubscriptions,omitempty"`
}

// NewScriptsConfigGet200ResponseSyncsInner instantiates a new ScriptsConfigGet200ResponseSyncsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScriptsConfigGet200ResponseSyncsInner() *ScriptsConfigGet200ResponseSyncsInner {
	this := ScriptsConfigGet200ResponseSyncsInner{}
	return &this
}

// NewScriptsConfigGet200ResponseSyncsInnerWithDefaults instantiates a new ScriptsConfigGet200ResponseSyncsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScriptsConfigGet200ResponseSyncsInnerWithDefaults() *ScriptsConfigGet200ResponseSyncsInner {
	this := ScriptsConfigGet200ResponseSyncsInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ScriptsConfigGet200ResponseSyncsInner) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ScriptsConfigGet200ResponseSyncsInner) SetType(v string) {
	o.Type = &v
}

// GetModels returns the Models field value if set, zero value otherwise.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetModels() []ScriptsConfigGet200ResponseSyncsInnerModelsInner {
	if o == nil || IsNil(o.Models) {
		var ret []ScriptsConfigGet200ResponseSyncsInnerModelsInner
		return ret
	}
	return o.Models
}

// GetModelsOk returns a tuple with the Models field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetModelsOk() ([]ScriptsConfigGet200ResponseSyncsInnerModelsInner, bool) {
	if o == nil || IsNil(o.Models) {
		return nil, false
	}
	return o.Models, true
}

// HasModels returns a boolean if a field has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) HasModels() bool {
	if o != nil && !IsNil(o.Models) {
		return true
	}

	return false
}

// SetModels gets a reference to the given []ScriptsConfigGet200ResponseSyncsInnerModelsInner and assigns it to the Models field.
func (o *ScriptsConfigGet200ResponseSyncsInner) SetModels(v []ScriptsConfigGet200ResponseSyncsInnerModelsInner) {
	o.Models = v
}

// GetSyncType returns the SyncType field value if set, zero value otherwise.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetSyncType() string {
	if o == nil || IsNil(o.SyncType) {
		var ret string
		return ret
	}
	return *o.SyncType
}

// GetSyncTypeOk returns a tuple with the SyncType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetSyncTypeOk() (*string, bool) {
	if o == nil || IsNil(o.SyncType) {
		return nil, false
	}
	return o.SyncType, true
}

// HasSyncType returns a boolean if a field has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) HasSyncType() bool {
	if o != nil && !IsNil(o.SyncType) {
		return true
	}

	return false
}

// SetSyncType gets a reference to the given string and assigns it to the SyncType field.
func (o *ScriptsConfigGet200ResponseSyncsInner) SetSyncType(v string) {
	o.SyncType = &v
}

// GetRuns returns the Runs field value if set, zero value otherwise.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetRuns() string {
	if o == nil || IsNil(o.Runs) {
		var ret string
		return ret
	}
	return *o.Runs
}

// GetRunsOk returns a tuple with the Runs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetRunsOk() (*string, bool) {
	if o == nil || IsNil(o.Runs) {
		return nil, false
	}
	return o.Runs, true
}

// HasRuns returns a boolean if a field has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) HasRuns() bool {
	if o != nil && !IsNil(o.Runs) {
		return true
	}

	return false
}

// SetRuns gets a reference to the given string and assigns it to the Runs field.
func (o *ScriptsConfigGet200ResponseSyncsInner) SetRuns(v string) {
	o.Runs = &v
}

// GetTrackDeletes returns the TrackDeletes field value if set, zero value otherwise.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetTrackDeletes() bool {
	if o == nil || IsNil(o.TrackDeletes) {
		var ret bool
		return ret
	}
	return *o.TrackDeletes
}

// GetTrackDeletesOk returns a tuple with the TrackDeletes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetTrackDeletesOk() (*bool, bool) {
	if o == nil || IsNil(o.TrackDeletes) {
		return nil, false
	}
	return o.TrackDeletes, true
}

// HasTrackDeletes returns a boolean if a field has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) HasTrackDeletes() bool {
	if o != nil && !IsNil(o.TrackDeletes) {
		return true
	}

	return false
}

// SetTrackDeletes gets a reference to the given bool and assigns it to the TrackDeletes field.
func (o *ScriptsConfigGet200ResponseSyncsInner) SetTrackDeletes(v bool) {
	o.TrackDeletes = &v
}

// GetAutoStart returns the AutoStart field value if set, zero value otherwise.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetAutoStart() bool {
	if o == nil || IsNil(o.AutoStart) {
		var ret bool
		return ret
	}
	return *o.AutoStart
}

// GetAutoStartOk returns a tuple with the AutoStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetAutoStartOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoStart) {
		return nil, false
	}
	return o.AutoStart, true
}

// HasAutoStart returns a boolean if a field has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) HasAutoStart() bool {
	if o != nil && !IsNil(o.AutoStart) {
		return true
	}

	return false
}

// SetAutoStart gets a reference to the given bool and assigns it to the AutoStart field.
func (o *ScriptsConfigGet200ResponseSyncsInner) SetAutoStart(v bool) {
	o.AutoStart = &v
}

// GetLastDeployed returns the LastDeployed field value if set, zero value otherwise.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetLastDeployed() string {
	if o == nil || IsNil(o.LastDeployed) {
		var ret string
		return ret
	}
	return *o.LastDeployed
}

// GetLastDeployedOk returns a tuple with the LastDeployed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetLastDeployedOk() (*string, bool) {
	if o == nil || IsNil(o.LastDeployed) {
		return nil, false
	}
	return o.LastDeployed, true
}

// HasLastDeployed returns a boolean if a field has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) HasLastDeployed() bool {
	if o != nil && !IsNil(o.LastDeployed) {
		return true
	}

	return false
}

// SetLastDeployed gets a reference to the given string and assigns it to the LastDeployed field.
func (o *ScriptsConfigGet200ResponseSyncsInner) SetLastDeployed(v string) {
	o.LastDeployed = &v
}

// GetIsPublic returns the IsPublic field value if set, zero value otherwise.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetIsPublic() bool {
	if o == nil || IsNil(o.IsPublic) {
		var ret bool
		return ret
	}
	return *o.IsPublic
}

// GetIsPublicOk returns a tuple with the IsPublic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetIsPublicOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPublic) {
		return nil, false
	}
	return o.IsPublic, true
}

// HasIsPublic returns a boolean if a field has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) HasIsPublic() bool {
	if o != nil && !IsNil(o.IsPublic) {
		return true
	}

	return false
}

// SetIsPublic gets a reference to the given bool and assigns it to the IsPublic field.
func (o *ScriptsConfigGet200ResponseSyncsInner) SetIsPublic(v bool) {
	o.IsPublic = &v
}

// GetPreBuilt returns the PreBuilt field value if set, zero value otherwise.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetPreBuilt() bool {
	if o == nil || IsNil(o.PreBuilt) {
		var ret bool
		return ret
	}
	return *o.PreBuilt
}

// GetPreBuiltOk returns a tuple with the PreBuilt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetPreBuiltOk() (*bool, bool) {
	if o == nil || IsNil(o.PreBuilt) {
		return nil, false
	}
	return o.PreBuilt, true
}

// HasPreBuilt returns a boolean if a field has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) HasPreBuilt() bool {
	if o != nil && !IsNil(o.PreBuilt) {
		return true
	}

	return false
}

// SetPreBuilt gets a reference to the given bool and assigns it to the PreBuilt field.
func (o *ScriptsConfigGet200ResponseSyncsInner) SetPreBuilt(v bool) {
	o.PreBuilt = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *ScriptsConfigGet200ResponseSyncsInner) SetVersion(v string) {
	o.Version = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetAttributes() map[string]interface{} {
	if o == nil || IsNil(o.Attributes) {
		var ret map[string]interface{}
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetAttributesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Attributes) {
		return map[string]interface{}{}, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]interface{} and assigns it to the Attributes field.
func (o *ScriptsConfigGet200ResponseSyncsInner) SetAttributes(v map[string]interface{}) {
	o.Attributes = v
}

// GetInput returns the Input field value if set, zero value otherwise.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetInput() map[string]interface{} {
	if o == nil || IsNil(o.Input) {
		var ret map[string]interface{}
		return ret
	}
	return o.Input
}

// GetInputOk returns a tuple with the Input field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetInputOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Input) {
		return map[string]interface{}{}, false
	}
	return o.Input, true
}

// HasInput returns a boolean if a field has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) HasInput() bool {
	if o != nil && !IsNil(o.Input) {
		return true
	}

	return false
}

// SetInput gets a reference to the given map[string]interface{} and assigns it to the Input field.
func (o *ScriptsConfigGet200ResponseSyncsInner) SetInput(v map[string]interface{}) {
	o.Input = v
}

// GetReturns returns the Returns field value if set, zero value otherwise.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetReturns() []string {
	if o == nil || IsNil(o.Returns) {
		var ret []string
		return ret
	}
	return o.Returns
}

// GetReturnsOk returns a tuple with the Returns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetReturnsOk() ([]string, bool) {
	if o == nil || IsNil(o.Returns) {
		return nil, false
	}
	return o.Returns, true
}

// HasReturns returns a boolean if a field has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) HasReturns() bool {
	if o != nil && !IsNil(o.Returns) {
		return true
	}

	return false
}

// SetReturns gets a reference to the given []string and assigns it to the Returns field.
func (o *ScriptsConfigGet200ResponseSyncsInner) SetReturns(v []string) {
	o.Returns = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ScriptsConfigGet200ResponseSyncsInner) SetDescription(v string) {
	o.Description = &v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetScopes() []string {
	if o == nil || IsNil(o.Scopes) {
		var ret []string
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetScopesOk() ([]string, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []string and assigns it to the Scopes field.
func (o *ScriptsConfigGet200ResponseSyncsInner) SetScopes(v []string) {
	o.Scopes = v
}

// GetEndpoints returns the Endpoints field value if set, zero value otherwise.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetEndpoints() []map[string]interface{} {
	if o == nil || IsNil(o.Endpoints) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Endpoints
}

// GetEndpointsOk returns a tuple with the Endpoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetEndpointsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Endpoints) {
		return nil, false
	}
	return o.Endpoints, true
}

// HasEndpoints returns a boolean if a field has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) HasEndpoints() bool {
	if o != nil && !IsNil(o.Endpoints) {
		return true
	}

	return false
}

// SetEndpoints gets a reference to the given []map[string]interface{} and assigns it to the Endpoints field.
func (o *ScriptsConfigGet200ResponseSyncsInner) SetEndpoints(v []map[string]interface{}) {
	o.Endpoints = v
}

// GetNangoYamlVersion returns the NangoYamlVersion field value if set, zero value otherwise.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetNangoYamlVersion() string {
	if o == nil || IsNil(o.NangoYamlVersion) {
		var ret string
		return ret
	}
	return *o.NangoYamlVersion
}

// GetNangoYamlVersionOk returns a tuple with the NangoYamlVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetNangoYamlVersionOk() (*string, bool) {
	if o == nil || IsNil(o.NangoYamlVersion) {
		return nil, false
	}
	return o.NangoYamlVersion, true
}

// HasNangoYamlVersion returns a boolean if a field has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) HasNangoYamlVersion() bool {
	if o != nil && !IsNil(o.NangoYamlVersion) {
		return true
	}

	return false
}

// SetNangoYamlVersion gets a reference to the given string and assigns it to the NangoYamlVersion field.
func (o *ScriptsConfigGet200ResponseSyncsInner) SetNangoYamlVersion(v string) {
	o.NangoYamlVersion = &v
}

// GetWebhookSubscriptions returns the WebhookSubscriptions field value if set, zero value otherwise.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetWebhookSubscriptions() []string {
	if o == nil || IsNil(o.WebhookSubscriptions) {
		var ret []string
		return ret
	}
	return o.WebhookSubscriptions
}

// GetWebhookSubscriptionsOk returns a tuple with the WebhookSubscriptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) GetWebhookSubscriptionsOk() ([]string, bool) {
	if o == nil || IsNil(o.WebhookSubscriptions) {
		return nil, false
	}
	return o.WebhookSubscriptions, true
}

// HasWebhookSubscriptions returns a boolean if a field has been set.
func (o *ScriptsConfigGet200ResponseSyncsInner) HasWebhookSubscriptions() bool {
	if o != nil && !IsNil(o.WebhookSubscriptions) {
		return true
	}

	return false
}

// SetWebhookSubscriptions gets a reference to the given []string and assigns it to the WebhookSubscriptions field.
func (o *ScriptsConfigGet200ResponseSyncsInner) SetWebhookSubscriptions(v []string) {
	o.WebhookSubscriptions = v
}

func (o ScriptsConfigGet200ResponseSyncsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScriptsConfigGet200ResponseSyncsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Models) {
		toSerialize["models"] = o.Models
	}
	if !IsNil(o.SyncType) {
		toSerialize["sync_type"] = o.SyncType
	}
	if !IsNil(o.Runs) {
		toSerialize["runs"] = o.Runs
	}
	if !IsNil(o.TrackDeletes) {
		toSerialize["track_deletes"] = o.TrackDeletes
	}
	if !IsNil(o.AutoStart) {
		toSerialize["auto_start"] = o.AutoStart
	}
	if !IsNil(o.LastDeployed) {
		toSerialize["last_deployed"] = o.LastDeployed
	}
	if !IsNil(o.IsPublic) {
		toSerialize["is_public"] = o.IsPublic
	}
	if !IsNil(o.PreBuilt) {
		toSerialize["pre_built"] = o.PreBuilt
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	if !IsNil(o.Input) {
		toSerialize["input"] = o.Input
	}
	if !IsNil(o.Returns) {
		toSerialize["returns"] = o.Returns
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}
	if !IsNil(o.Endpoints) {
		toSerialize["endpoints"] = o.Endpoints
	}
	if !IsNil(o.NangoYamlVersion) {
		toSerialize["nango_yaml_version"] = o.NangoYamlVersion
	}
	if !IsNil(o.WebhookSubscriptions) {
		toSerialize["webhookSubscriptions"] = o.WebhookSubscriptions
	}
	return toSerialize, nil
}

type NullableScriptsConfigGet200ResponseSyncsInner struct {
	value *ScriptsConfigGet200ResponseSyncsInner
	isSet bool
}

func (v NullableScriptsConfigGet200ResponseSyncsInner) Get() *ScriptsConfigGet200ResponseSyncsInner {
	return v.value
}

func (v *NullableScriptsConfigGet200ResponseSyncsInner) Set(val *ScriptsConfigGet200ResponseSyncsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableScriptsConfigGet200ResponseSyncsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableScriptsConfigGet200ResponseSyncsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScriptsConfigGet200ResponseSyncsInner(val *ScriptsConfigGet200ResponseSyncsInner) *NullableScriptsConfigGet200ResponseSyncsInner {
	return &NullableScriptsConfigGet200ResponseSyncsInner{value: val, isSet: true}
}

func (v NullableScriptsConfigGet200ResponseSyncsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScriptsConfigGet200ResponseSyncsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


