/*
Nango API

Nango API specs used to authorize & sync data with external APIs.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nango

import (
	"encoding/json"
)

// checks if the EnvironmentVariablesGet200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvironmentVariablesGet200ResponseInner{}

// EnvironmentVariablesGet200ResponseInner struct for EnvironmentVariablesGet200ResponseInner
type EnvironmentVariablesGet200ResponseInner struct {
	// The name of the environment variable
	Name *string `json:"name,omitempty"`
	// The value of the environment variable
	Value *string `json:"value,omitempty"`
}

// NewEnvironmentVariablesGet200ResponseInner instantiates a new EnvironmentVariablesGet200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentVariablesGet200ResponseInner() *EnvironmentVariablesGet200ResponseInner {
	this := EnvironmentVariablesGet200ResponseInner{}
	return &this
}

// NewEnvironmentVariablesGet200ResponseInnerWithDefaults instantiates a new EnvironmentVariablesGet200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentVariablesGet200ResponseInnerWithDefaults() *EnvironmentVariablesGet200ResponseInner {
	this := EnvironmentVariablesGet200ResponseInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *EnvironmentVariablesGet200ResponseInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentVariablesGet200ResponseInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *EnvironmentVariablesGet200ResponseInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *EnvironmentVariablesGet200ResponseInner) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *EnvironmentVariablesGet200ResponseInner) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentVariablesGet200ResponseInner) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *EnvironmentVariablesGet200ResponseInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *EnvironmentVariablesGet200ResponseInner) SetValue(v string) {
	o.Value = &v
}

func (o EnvironmentVariablesGet200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvironmentVariablesGet200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableEnvironmentVariablesGet200ResponseInner struct {
	value *EnvironmentVariablesGet200ResponseInner
	isSet bool
}

func (v NullableEnvironmentVariablesGet200ResponseInner) Get() *EnvironmentVariablesGet200ResponseInner {
	return v.value
}

func (v *NullableEnvironmentVariablesGet200ResponseInner) Set(val *EnvironmentVariablesGet200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentVariablesGet200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentVariablesGet200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentVariablesGet200ResponseInner(val *EnvironmentVariablesGet200ResponseInner) *NullableEnvironmentVariablesGet200ResponseInner {
	return &NullableEnvironmentVariablesGet200ResponseInner{value: val, isSet: true}
}

func (v NullableEnvironmentVariablesGet200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentVariablesGet200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


