/*
Nango API

Nango API specs used to authorize & sync data with external APIs.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nango

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// ConnectionMetadataPost201ResponseConnectionId - struct for ConnectionMetadataPost201ResponseConnectionId
type ConnectionMetadataPost201ResponseConnectionId struct {
	ArrayOfString *[]string
	String *string
}

// []stringAsConnectionMetadataPost201ResponseConnectionId is a convenience function that returns []string wrapped in ConnectionMetadataPost201ResponseConnectionId
func ArrayOfStringAsConnectionMetadataPost201ResponseConnectionId(v *[]string) ConnectionMetadataPost201ResponseConnectionId {
	return ConnectionMetadataPost201ResponseConnectionId{
		ArrayOfString: v,
	}
}

// stringAsConnectionMetadataPost201ResponseConnectionId is a convenience function that returns string wrapped in ConnectionMetadataPost201ResponseConnectionId
func StringAsConnectionMetadataPost201ResponseConnectionId(v *string) ConnectionMetadataPost201ResponseConnectionId {
	return ConnectionMetadataPost201ResponseConnectionId{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ConnectionMetadataPost201ResponseConnectionId) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ArrayOfString
	err = newStrictDecoder(data).Decode(&dst.ArrayOfString)
	if err == nil {
		jsonArrayOfString, _ := json.Marshal(dst.ArrayOfString)
		if string(jsonArrayOfString) == "{}" { // empty struct
			dst.ArrayOfString = nil
		} else {
			if err = validator.Validate(dst.ArrayOfString); err != nil {
				dst.ArrayOfString = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfString = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ArrayOfString = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ConnectionMetadataPost201ResponseConnectionId)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ConnectionMetadataPost201ResponseConnectionId)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ConnectionMetadataPost201ResponseConnectionId) MarshalJSON() ([]byte, error) {
	if src.ArrayOfString != nil {
		return json.Marshal(&src.ArrayOfString)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ConnectionMetadataPost201ResponseConnectionId) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ArrayOfString != nil {
		return obj.ArrayOfString
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableConnectionMetadataPost201ResponseConnectionId struct {
	value *ConnectionMetadataPost201ResponseConnectionId
	isSet bool
}

func (v NullableConnectionMetadataPost201ResponseConnectionId) Get() *ConnectionMetadataPost201ResponseConnectionId {
	return v.value
}

func (v *NullableConnectionMetadataPost201ResponseConnectionId) Set(val *ConnectionMetadataPost201ResponseConnectionId) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionMetadataPost201ResponseConnectionId) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionMetadataPost201ResponseConnectionId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionMetadataPost201ResponseConnectionId(val *ConnectionMetadataPost201ResponseConnectionId) *NullableConnectionMetadataPost201ResponseConnectionId {
	return &NullableConnectionMetadataPost201ResponseConnectionId{value: val, isSet: true}
}

func (v NullableConnectionMetadataPost201ResponseConnectionId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionMetadataPost201ResponseConnectionId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


