/*
Nango API

Nango API specs used to authorize & sync data with external APIs.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nango

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// ConnectionMetadataPatchRequestConnectionId - struct for ConnectionMetadataPatchRequestConnectionId
type ConnectionMetadataPatchRequestConnectionId struct {
	ArrayOfString *[]string
	String *string
}

// []stringAsConnectionMetadataPatchRequestConnectionId is a convenience function that returns []string wrapped in ConnectionMetadataPatchRequestConnectionId
func ArrayOfStringAsConnectionMetadataPatchRequestConnectionId(v *[]string) ConnectionMetadataPatchRequestConnectionId {
	return ConnectionMetadataPatchRequestConnectionId{
		ArrayOfString: v,
	}
}

// stringAsConnectionMetadataPatchRequestConnectionId is a convenience function that returns string wrapped in ConnectionMetadataPatchRequestConnectionId
func StringAsConnectionMetadataPatchRequestConnectionId(v *string) ConnectionMetadataPatchRequestConnectionId {
	return ConnectionMetadataPatchRequestConnectionId{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ConnectionMetadataPatchRequestConnectionId) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ArrayOfString
	err = newStrictDecoder(data).Decode(&dst.ArrayOfString)
	if err == nil {
		jsonArrayOfString, _ := json.Marshal(dst.ArrayOfString)
		if string(jsonArrayOfString) == "{}" { // empty struct
			dst.ArrayOfString = nil
		} else {
			if err = validator.Validate(dst.ArrayOfString); err != nil {
				dst.ArrayOfString = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfString = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ArrayOfString = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ConnectionMetadataPatchRequestConnectionId)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ConnectionMetadataPatchRequestConnectionId)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ConnectionMetadataPatchRequestConnectionId) MarshalJSON() ([]byte, error) {
	if src.ArrayOfString != nil {
		return json.Marshal(&src.ArrayOfString)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ConnectionMetadataPatchRequestConnectionId) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ArrayOfString != nil {
		return obj.ArrayOfString
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableConnectionMetadataPatchRequestConnectionId struct {
	value *ConnectionMetadataPatchRequestConnectionId
	isSet bool
}

func (v NullableConnectionMetadataPatchRequestConnectionId) Get() *ConnectionMetadataPatchRequestConnectionId {
	return v.value
}

func (v *NullableConnectionMetadataPatchRequestConnectionId) Set(val *ConnectionMetadataPatchRequestConnectionId) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionMetadataPatchRequestConnectionId) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionMetadataPatchRequestConnectionId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionMetadataPatchRequestConnectionId(val *ConnectionMetadataPatchRequestConnectionId) *NullableConnectionMetadataPatchRequestConnectionId {
	return &NullableConnectionMetadataPatchRequestConnectionId{value: val, isSet: true}
}

func (v NullableConnectionMetadataPatchRequestConnectionId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionMetadataPatchRequestConnectionId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


