/*
Nango API

Nango API specs used to authorize & sync data with external APIs.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nango

import (
	"encoding/json"
)

// checks if the RecordsGet200ResponseRecordsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecordsGet200ResponseRecordsInner{}

// RecordsGet200ResponseRecordsInner struct for RecordsGet200ResponseRecordsInner
type RecordsGet200ResponseRecordsInner struct {
	// The data Nango synced in for you
	YourProperties *string `json:"your-properties,omitempty"`
	NangoMetadata *RecordsGet200ResponseRecordsInnerNangoMetadata `json:"_nango_metadata,omitempty"`
}

// NewRecordsGet200ResponseRecordsInner instantiates a new RecordsGet200ResponseRecordsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecordsGet200ResponseRecordsInner() *RecordsGet200ResponseRecordsInner {
	this := RecordsGet200ResponseRecordsInner{}
	return &this
}

// NewRecordsGet200ResponseRecordsInnerWithDefaults instantiates a new RecordsGet200ResponseRecordsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecordsGet200ResponseRecordsInnerWithDefaults() *RecordsGet200ResponseRecordsInner {
	this := RecordsGet200ResponseRecordsInner{}
	return &this
}

// GetYourProperties returns the YourProperties field value if set, zero value otherwise.
func (o *RecordsGet200ResponseRecordsInner) GetYourProperties() string {
	if o == nil || IsNil(o.YourProperties) {
		var ret string
		return ret
	}
	return *o.YourProperties
}

// GetYourPropertiesOk returns a tuple with the YourProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecordsGet200ResponseRecordsInner) GetYourPropertiesOk() (*string, bool) {
	if o == nil || IsNil(o.YourProperties) {
		return nil, false
	}
	return o.YourProperties, true
}

// HasYourProperties returns a boolean if a field has been set.
func (o *RecordsGet200ResponseRecordsInner) HasYourProperties() bool {
	if o != nil && !IsNil(o.YourProperties) {
		return true
	}

	return false
}

// SetYourProperties gets a reference to the given string and assigns it to the YourProperties field.
func (o *RecordsGet200ResponseRecordsInner) SetYourProperties(v string) {
	o.YourProperties = &v
}

// GetNangoMetadata returns the NangoMetadata field value if set, zero value otherwise.
func (o *RecordsGet200ResponseRecordsInner) GetNangoMetadata() RecordsGet200ResponseRecordsInnerNangoMetadata {
	if o == nil || IsNil(o.NangoMetadata) {
		var ret RecordsGet200ResponseRecordsInnerNangoMetadata
		return ret
	}
	return *o.NangoMetadata
}

// GetNangoMetadataOk returns a tuple with the NangoMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecordsGet200ResponseRecordsInner) GetNangoMetadataOk() (*RecordsGet200ResponseRecordsInnerNangoMetadata, bool) {
	if o == nil || IsNil(o.NangoMetadata) {
		return nil, false
	}
	return o.NangoMetadata, true
}

// HasNangoMetadata returns a boolean if a field has been set.
func (o *RecordsGet200ResponseRecordsInner) HasNangoMetadata() bool {
	if o != nil && !IsNil(o.NangoMetadata) {
		return true
	}

	return false
}

// SetNangoMetadata gets a reference to the given RecordsGet200ResponseRecordsInnerNangoMetadata and assigns it to the NangoMetadata field.
func (o *RecordsGet200ResponseRecordsInner) SetNangoMetadata(v RecordsGet200ResponseRecordsInnerNangoMetadata) {
	o.NangoMetadata = &v
}

func (o RecordsGet200ResponseRecordsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecordsGet200ResponseRecordsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.YourProperties) {
		toSerialize["your-properties"] = o.YourProperties
	}
	if !IsNil(o.NangoMetadata) {
		toSerialize["_nango_metadata"] = o.NangoMetadata
	}
	return toSerialize, nil
}

type NullableRecordsGet200ResponseRecordsInner struct {
	value *RecordsGet200ResponseRecordsInner
	isSet bool
}

func (v NullableRecordsGet200ResponseRecordsInner) Get() *RecordsGet200ResponseRecordsInner {
	return v.value
}

func (v *NullableRecordsGet200ResponseRecordsInner) Set(val *RecordsGet200ResponseRecordsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableRecordsGet200ResponseRecordsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableRecordsGet200ResponseRecordsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecordsGet200ResponseRecordsInner(val *RecordsGet200ResponseRecordsInner) *NullableRecordsGet200ResponseRecordsInner {
	return &NullableRecordsGet200ResponseRecordsInner{value: val, isSet: true}
}

func (v NullableRecordsGet200ResponseRecordsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecordsGet200ResponseRecordsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


