/*
Nango API

Nango API specs used to authorize & sync data with external APIs.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nango

import (
	"encoding/json"
)

// checks if the ConfigProviderConfigKeyGet200ResponseConfigSyncsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigProviderConfigKeyGet200ResponseConfigSyncsInner{}

// ConfigProviderConfigKeyGet200ResponseConfigSyncsInner struct for ConfigProviderConfigKeyGet200ResponseConfigSyncsInner
type ConfigProviderConfigKeyGet200ResponseConfigSyncsInner struct {
	// The name of the sync.
	Name *string `json:"name,omitempty"`
	// The creation timestamp of the sync.
	CreatedAt *string `json:"created_at,omitempty"`
	// The last updated timestamp of the sync.
	UpdatedAt *string `json:"updated_at,omitempty"`
	// Description of what the sync does and details about it
	Description *string `json:"description,omitempty"`
}

// NewConfigProviderConfigKeyGet200ResponseConfigSyncsInner instantiates a new ConfigProviderConfigKeyGet200ResponseConfigSyncsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigProviderConfigKeyGet200ResponseConfigSyncsInner() *ConfigProviderConfigKeyGet200ResponseConfigSyncsInner {
	this := ConfigProviderConfigKeyGet200ResponseConfigSyncsInner{}
	return &this
}

// NewConfigProviderConfigKeyGet200ResponseConfigSyncsInnerWithDefaults instantiates a new ConfigProviderConfigKeyGet200ResponseConfigSyncsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigProviderConfigKeyGet200ResponseConfigSyncsInnerWithDefaults() *ConfigProviderConfigKeyGet200ResponseConfigSyncsInner {
	this := ConfigProviderConfigKeyGet200ResponseConfigSyncsInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ConfigProviderConfigKeyGet200ResponseConfigSyncsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigProviderConfigKeyGet200ResponseConfigSyncsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ConfigProviderConfigKeyGet200ResponseConfigSyncsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ConfigProviderConfigKeyGet200ResponseConfigSyncsInner) SetName(v string) {
	o.Name = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ConfigProviderConfigKeyGet200ResponseConfigSyncsInner) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigProviderConfigKeyGet200ResponseConfigSyncsInner) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ConfigProviderConfigKeyGet200ResponseConfigSyncsInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ConfigProviderConfigKeyGet200ResponseConfigSyncsInner) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ConfigProviderConfigKeyGet200ResponseConfigSyncsInner) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigProviderConfigKeyGet200ResponseConfigSyncsInner) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ConfigProviderConfigKeyGet200ResponseConfigSyncsInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *ConfigProviderConfigKeyGet200ResponseConfigSyncsInner) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ConfigProviderConfigKeyGet200ResponseConfigSyncsInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigProviderConfigKeyGet200ResponseConfigSyncsInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ConfigProviderConfigKeyGet200ResponseConfigSyncsInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ConfigProviderConfigKeyGet200ResponseConfigSyncsInner) SetDescription(v string) {
	o.Description = &v
}

func (o ConfigProviderConfigKeyGet200ResponseConfigSyncsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigProviderConfigKeyGet200ResponseConfigSyncsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableConfigProviderConfigKeyGet200ResponseConfigSyncsInner struct {
	value *ConfigProviderConfigKeyGet200ResponseConfigSyncsInner
	isSet bool
}

func (v NullableConfigProviderConfigKeyGet200ResponseConfigSyncsInner) Get() *ConfigProviderConfigKeyGet200ResponseConfigSyncsInner {
	return v.value
}

func (v *NullableConfigProviderConfigKeyGet200ResponseConfigSyncsInner) Set(val *ConfigProviderConfigKeyGet200ResponseConfigSyncsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigProviderConfigKeyGet200ResponseConfigSyncsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigProviderConfigKeyGet200ResponseConfigSyncsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigProviderConfigKeyGet200ResponseConfigSyncsInner(val *ConfigProviderConfigKeyGet200ResponseConfigSyncsInner) *NullableConfigProviderConfigKeyGet200ResponseConfigSyncsInner {
	return &NullableConfigProviderConfigKeyGet200ResponseConfigSyncsInner{value: val, isSet: true}
}

func (v NullableConfigProviderConfigKeyGet200ResponseConfigSyncsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigProviderConfigKeyGet200ResponseConfigSyncsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


