/*
Nango API

Nango API specs used to authorize & sync data with external APIs.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nango

import (
	"encoding/json"
)

// checks if the ConfigPut400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigPut400Response{}

// ConfigPut400Response struct for ConfigPut400Response
type ConfigPut400Response struct {
	Message *string `json:"message,omitempty"`
}

// NewConfigPut400Response instantiates a new ConfigPut400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigPut400Response() *ConfigPut400Response {
	this := ConfigPut400Response{}
	return &this
}

// NewConfigPut400ResponseWithDefaults instantiates a new ConfigPut400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigPut400ResponseWithDefaults() *ConfigPut400Response {
	this := ConfigPut400Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ConfigPut400Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPut400Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ConfigPut400Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ConfigPut400Response) SetMessage(v string) {
	o.Message = &v
}

func (o ConfigPut400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigPut400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableConfigPut400Response struct {
	value *ConfigPut400Response
	isSet bool
}

func (v NullableConfigPut400Response) Get() *ConfigPut400Response {
	return v.value
}

func (v *NullableConfigPut400Response) Set(val *ConfigPut400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigPut400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigPut400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigPut400Response(val *ConfigPut400Response) *NullableConfigPut400Response {
	return &NullableConfigPut400Response{value: val, isSet: true}
}

func (v NullableConfigPut400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigPut400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


