/*
Nango API

Nango API specs used to authorize & sync data with external APIs.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nango

import (
	"encoding/json"
)

// checks if the SyncRecordsGet200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SyncRecordsGet200ResponseInner{}

// SyncRecordsGet200ResponseInner struct for SyncRecordsGet200ResponseInner
type SyncRecordsGet200ResponseInner struct {
	// The data Nango synced in for you
	YourProperties *string `json:"your-properties,omitempty"`
	NangoMetadata *SyncRecordsGet200ResponseInnerNangoMetadata `json:"_nango_metadata,omitempty"`
}

// NewSyncRecordsGet200ResponseInner instantiates a new SyncRecordsGet200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyncRecordsGet200ResponseInner() *SyncRecordsGet200ResponseInner {
	this := SyncRecordsGet200ResponseInner{}
	return &this
}

// NewSyncRecordsGet200ResponseInnerWithDefaults instantiates a new SyncRecordsGet200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyncRecordsGet200ResponseInnerWithDefaults() *SyncRecordsGet200ResponseInner {
	this := SyncRecordsGet200ResponseInner{}
	return &this
}

// GetYourProperties returns the YourProperties field value if set, zero value otherwise.
func (o *SyncRecordsGet200ResponseInner) GetYourProperties() string {
	if o == nil || IsNil(o.YourProperties) {
		var ret string
		return ret
	}
	return *o.YourProperties
}

// GetYourPropertiesOk returns a tuple with the YourProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyncRecordsGet200ResponseInner) GetYourPropertiesOk() (*string, bool) {
	if o == nil || IsNil(o.YourProperties) {
		return nil, false
	}
	return o.YourProperties, true
}

// HasYourProperties returns a boolean if a field has been set.
func (o *SyncRecordsGet200ResponseInner) HasYourProperties() bool {
	if o != nil && !IsNil(o.YourProperties) {
		return true
	}

	return false
}

// SetYourProperties gets a reference to the given string and assigns it to the YourProperties field.
func (o *SyncRecordsGet200ResponseInner) SetYourProperties(v string) {
	o.YourProperties = &v
}

// GetNangoMetadata returns the NangoMetadata field value if set, zero value otherwise.
func (o *SyncRecordsGet200ResponseInner) GetNangoMetadata() SyncRecordsGet200ResponseInnerNangoMetadata {
	if o == nil || IsNil(o.NangoMetadata) {
		var ret SyncRecordsGet200ResponseInnerNangoMetadata
		return ret
	}
	return *o.NangoMetadata
}

// GetNangoMetadataOk returns a tuple with the NangoMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyncRecordsGet200ResponseInner) GetNangoMetadataOk() (*SyncRecordsGet200ResponseInnerNangoMetadata, bool) {
	if o == nil || IsNil(o.NangoMetadata) {
		return nil, false
	}
	return o.NangoMetadata, true
}

// HasNangoMetadata returns a boolean if a field has been set.
func (o *SyncRecordsGet200ResponseInner) HasNangoMetadata() bool {
	if o != nil && !IsNil(o.NangoMetadata) {
		return true
	}

	return false
}

// SetNangoMetadata gets a reference to the given SyncRecordsGet200ResponseInnerNangoMetadata and assigns it to the NangoMetadata field.
func (o *SyncRecordsGet200ResponseInner) SetNangoMetadata(v SyncRecordsGet200ResponseInnerNangoMetadata) {
	o.NangoMetadata = &v
}

func (o SyncRecordsGet200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SyncRecordsGet200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.YourProperties) {
		toSerialize["your-properties"] = o.YourProperties
	}
	if !IsNil(o.NangoMetadata) {
		toSerialize["_nango_metadata"] = o.NangoMetadata
	}
	return toSerialize, nil
}

type NullableSyncRecordsGet200ResponseInner struct {
	value *SyncRecordsGet200ResponseInner
	isSet bool
}

func (v NullableSyncRecordsGet200ResponseInner) Get() *SyncRecordsGet200ResponseInner {
	return v.value
}

func (v *NullableSyncRecordsGet200ResponseInner) Set(val *SyncRecordsGet200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSyncRecordsGet200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSyncRecordsGet200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyncRecordsGet200ResponseInner(val *SyncRecordsGet200ResponseInner) *NullableSyncRecordsGet200ResponseInner {
	return &NullableSyncRecordsGet200ResponseInner{value: val, isSet: true}
}

func (v NullableSyncRecordsGet200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyncRecordsGet200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


