/*
Nango API

Nango API specs used to authorize & sync data with external APIs.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nango

import (
	"encoding/json"
)

// checks if the ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner{}

// ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner struct for ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner
type ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner struct {
	Name *string `json:"name,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner instantiates a new ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner() *ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner {
	this := ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner{}
	return &this
}

// NewScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInnerWithDefaults instantiates a new ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInnerWithDefaults() *ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner {
	this := ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner) SetType(v string) {
	o.Type = &v
}

func (o ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner struct {
	value *ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner
	isSet bool
}

func (v NullableScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner) Get() *ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner {
	return v.value
}

func (v *NullableScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner) Set(val *ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner(val *ScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner) *NullableScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner {
	return &NullableScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner{value: val, isSet: true}
}

func (v NullableScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScriptsConfigGet200ResponseActionsInnerModelsInnerFieldsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


