/*
Nango API

Nango API specs used to authorize & sync data with external APIs.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nango

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConfigProviderConfigKeyGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigProviderConfigKeyGet200Response{}

// ConfigProviderConfigKeyGet200Response struct for ConfigProviderConfigKeyGet200Response
type ConfigProviderConfigKeyGet200Response struct {
	Config ConfigProviderConfigKeyGet200ResponseConfig `json:"config"`
}

type _ConfigProviderConfigKeyGet200Response ConfigProviderConfigKeyGet200Response

// NewConfigProviderConfigKeyGet200Response instantiates a new ConfigProviderConfigKeyGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigProviderConfigKeyGet200Response(config ConfigProviderConfigKeyGet200ResponseConfig) *ConfigProviderConfigKeyGet200Response {
	this := ConfigProviderConfigKeyGet200Response{}
	this.Config = config
	return &this
}

// NewConfigProviderConfigKeyGet200ResponseWithDefaults instantiates a new ConfigProviderConfigKeyGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigProviderConfigKeyGet200ResponseWithDefaults() *ConfigProviderConfigKeyGet200Response {
	this := ConfigProviderConfigKeyGet200Response{}
	return &this
}

// GetConfig returns the Config field value
func (o *ConfigProviderConfigKeyGet200Response) GetConfig() ConfigProviderConfigKeyGet200ResponseConfig {
	if o == nil {
		var ret ConfigProviderConfigKeyGet200ResponseConfig
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *ConfigProviderConfigKeyGet200Response) GetConfigOk() (*ConfigProviderConfigKeyGet200ResponseConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Config, true
}

// SetConfig sets field value
func (o *ConfigProviderConfigKeyGet200Response) SetConfig(v ConfigProviderConfigKeyGet200ResponseConfig) {
	o.Config = v
}

func (o ConfigProviderConfigKeyGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigProviderConfigKeyGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["config"] = o.Config
	return toSerialize, nil
}

func (o *ConfigProviderConfigKeyGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"config",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigProviderConfigKeyGet200Response := _ConfigProviderConfigKeyGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfigProviderConfigKeyGet200Response)

	if err != nil {
		return err
	}

	*o = ConfigProviderConfigKeyGet200Response(varConfigProviderConfigKeyGet200Response)

	return err
}

type NullableConfigProviderConfigKeyGet200Response struct {
	value *ConfigProviderConfigKeyGet200Response
	isSet bool
}

func (v NullableConfigProviderConfigKeyGet200Response) Get() *ConfigProviderConfigKeyGet200Response {
	return v.value
}

func (v *NullableConfigProviderConfigKeyGet200Response) Set(val *ConfigProviderConfigKeyGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigProviderConfigKeyGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigProviderConfigKeyGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigProviderConfigKeyGet200Response(val *ConfigProviderConfigKeyGet200Response) *NullableConfigProviderConfigKeyGet200Response {
	return &NullableConfigProviderConfigKeyGet200Response{value: val, isSet: true}
}

func (v NullableConfigProviderConfigKeyGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigProviderConfigKeyGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


