/*
Nango API

Nango API specs used to authorize & sync data with external APIs.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nango

import (
	"encoding/json"
)

// checks if the ActionTriggerPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActionTriggerPost200Response{}

// ActionTriggerPost200Response struct for ActionTriggerPost200Response
type ActionTriggerPost200Response struct {
	// The data returned by the action
	YourProperties *string `json:"your-properties,omitempty"`
}

// NewActionTriggerPost200Response instantiates a new ActionTriggerPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionTriggerPost200Response() *ActionTriggerPost200Response {
	this := ActionTriggerPost200Response{}
	return &this
}

// NewActionTriggerPost200ResponseWithDefaults instantiates a new ActionTriggerPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionTriggerPost200ResponseWithDefaults() *ActionTriggerPost200Response {
	this := ActionTriggerPost200Response{}
	return &this
}

// GetYourProperties returns the YourProperties field value if set, zero value otherwise.
func (o *ActionTriggerPost200Response) GetYourProperties() string {
	if o == nil || IsNil(o.YourProperties) {
		var ret string
		return ret
	}
	return *o.YourProperties
}

// GetYourPropertiesOk returns a tuple with the YourProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActionTriggerPost200Response) GetYourPropertiesOk() (*string, bool) {
	if o == nil || IsNil(o.YourProperties) {
		return nil, false
	}
	return o.YourProperties, true
}

// HasYourProperties returns a boolean if a field has been set.
func (o *ActionTriggerPost200Response) HasYourProperties() bool {
	if o != nil && !IsNil(o.YourProperties) {
		return true
	}

	return false
}

// SetYourProperties gets a reference to the given string and assigns it to the YourProperties field.
func (o *ActionTriggerPost200Response) SetYourProperties(v string) {
	o.YourProperties = &v
}

func (o ActionTriggerPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActionTriggerPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.YourProperties) {
		toSerialize["your-properties"] = o.YourProperties
	}
	return toSerialize, nil
}

type NullableActionTriggerPost200Response struct {
	value *ActionTriggerPost200Response
	isSet bool
}

func (v NullableActionTriggerPost200Response) Get() *ActionTriggerPost200Response {
	return v.value
}

func (v *NullableActionTriggerPost200Response) Set(val *ActionTriggerPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableActionTriggerPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableActionTriggerPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionTriggerPost200Response(val *ActionTriggerPost200Response) *NullableActionTriggerPost200Response {
	return &NullableActionTriggerPost200Response{value: val, isSet: true}
}

func (v NullableActionTriggerPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionTriggerPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


